<a href="https://colab.research.google.com/github/minette3762/FundDeepPyTorch/blob/main/Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor





In [1]:
# Import PyTorch
import torch

In [2]:
# Random tensor
torch.rand(2,2)

tensor([[0.1928, 0.5583],
        [0.5778, 0.5541]])

In [3]:
# Convert from 'List'
mylist = [[1,2],[3,4]]
torch.tensor(mylist)

tensor([[1, 2],
        [3, 4]])

In [5]:
mytensor = torch.tensor(mylist)
mytensor[1][1]

tensor(4)

In [6]:
mytensor[1][1] = -10
mytensor

tensor([[  1,   2],
        [  3, -10]])

In [8]:
# Special tensor
onestensor = torch.ones(3,3)
onestensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
zerostensor = torch.zeros(3,3)
zerostensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
# Operation
sumtensor = mytensor + torch.tensor([[1,2],[3,10]])
sumtensor

tensor([[2, 4],
        [6, 0]])

In [15]:
sumtensor.max()

tensor(6)

In [18]:
sumtensor.min().item()

0

In [20]:
floattensor = sumtensor.to(dtype=torch.float64)
floattensor

tensor([[2., 4.],
        [6., 0.]], dtype=torch.float64)

In [21]:
# Store the copied
logtensor = floattensor.log2()
logtensor

tensor([[1.0000, 2.0000],
        [2.5850,   -inf]], dtype=torch.float64)

In [22]:
floattensor.log2_()

tensor([[1.0000, 2.0000],
        [2.5850,   -inf]], dtype=torch.float64)