<a href="https://colab.research.google.com/github/minette3762/FundDeepPyTorch/blob/main/Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor





In [1]:
# Import PyTorch
import torch

In [2]:
# Random tensor
torch.rand(2,2)

tensor([[0.1928, 0.5583],
        [0.5778, 0.5541]])

In [3]:
# Convert from 'List'
mylist = [[1,2],[3,4]]
torch.tensor(mylist)

tensor([[1, 2],
        [3, 4]])

In [5]:
mytensor = torch.tensor(mylist)
mytensor[1][1]

tensor(4)

In [6]:
mytensor[1][1] = -10
mytensor

tensor([[  1,   2],
        [  3, -10]])

In [8]:
# Special tensor
onestensor = torch.ones(3,3)
onestensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
zerostensor = torch.zeros(3,3)
zerostensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
# Operation
sumtensor = mytensor + torch.tensor([[1,2],[3,10]])
sumtensor

tensor([[2, 4],
        [6, 0]])

In [15]:
sumtensor.max()

tensor(6)

In [18]:
sumtensor.min().item()

0

In [20]:
floattensor = sumtensor.to(dtype=torch.float64)
floattensor

tensor([[2., 4.],
        [6., 0.]], dtype=torch.float64)

In [21]:
# Store the copied
logtensor = floattensor.log2()
logtensor

tensor([[1.0000, 2.0000],
        [2.5850,   -inf]], dtype=torch.float64)

In [22]:
floattensor.log2_()

tensor([[1.0000, 2.0000],
        [2.5850,   -inf]], dtype=torch.float64)

## Exercise
(Generated from Gemini)
1. **Comprehension**

- สร้าง Tensor ชื่อ scores จากข้อมูล List นี้: [[80, 75], [90, 65]]

- พบว่าคะแนนตัวแรก (80) บันทึกผิด ให้แก้ค่าที่ตำแหน่ง [0][0] เป็น 85

- สร้าง Tensor ที่มีค่าเป็น 1 ทั้งหมด (Ones Tensor) ขนาด 2x2 ชื่อ bonus

- นำคะแนน scores บวกกับคะแนนพิเศษ bonus เก็บไว้ในตัวแปรใหม่ชื่อ final_scores

- หาค่าคะแนนสูงสุด (Max) จาก final_scores และดึงค่าออกมาเป็นตัวเลข Python ธรรมดา (ใช้ .item())

In [30]:
scoreslist = [[80, 75], [90, 65]]
scores = torch.tensor(scoreslist)
scores

tensor([[80, 75],
        [90, 65]])

In [31]:
scores[0][0] = 85
scores

tensor([[85, 75],
        [90, 65]])

In [32]:
bonus = torch.ones(2,2)
final_scores = scores+bonus
final_scores

tensor([[86., 76.],
        [91., 66.]])

In [33]:
final_scores.max().item()

91.0

2. **Challenge**

- สร้าง Tensor สุ่ม (Random) ขนาด 3x3 เก็บไว้ในตัวแปร raw_data

- แปลงชนิดข้อมูล (Data Type) ของ raw_data ให้เป็น torch.float64 เพื่อความละเอียดสูง

- ทำการคำนวณ Logarithm ฐาน 2 ของ raw_data แต่ให้เก็บผลลัพธ์ลงในตัวแปรใหม่ชื่อ processed_data (ห้ามแก้ตัวแปรเดิม)

- ให้ทำการคำนวณ Logarithm ฐาน 2 อีกครั้งกับ processed_data แต่ครั้งนี้ให้ทำแบบ In-place (แก้ไขค่าในตัวแปรเดิมทันที ไม่ต้องสร้างตัวแปรรับ)

- ตรวจสอบผลลัพธ์โดยการปริ้นค่า processed_data ออกมา

In [39]:
raw_data = torch.rand(3,3)
raw_data = raw_data.to(dtype = torch.float64)
raw_data

tensor([[0.6819, 0.9613, 0.0098],
        [0.4218, 0.7353, 0.4570],
        [0.8960, 0.4717, 0.7440]], dtype=torch.float64)

In [40]:
processed_data = raw_data.log2()
processed_data

tensor([[-0.5524, -0.0569, -6.6707],
        [-1.2453, -0.4436, -1.1297],
        [-0.1584, -1.0841, -0.4266]], dtype=torch.float64)

In [41]:
processed_data.log2_()
processed_data

tensor([[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]], dtype=torch.float64)

3. **Unseen**

- Create a tensor named data containing a sequence of integers from 1 to 12 using torch.arange().

- Reshape this 1D tensor into a 2D matrix with dimensions (3 rows, 4 columns).

- Calculate the sum of each row and print the result.

- Filter and Replace: Find all elements in the data matrix that are even numbers (divisible by 2) and replace them with 0. Print the final matrix.

In [44]:
data = torch.arange(1,13)
data

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
matrix = data.reshape(3,4)
matrix

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [46]:
matrix.sum(dim=1)

tensor([10, 26, 42])

In [47]:
matrix[matrix%2 == 0] = 0
matrix

tensor([[ 1,  0,  3,  0],
        [ 5,  0,  7,  0],
        [ 9,  0, 11,  0]])